/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InitialData;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Reserva;

/**
 *
 * @author Ivan
 */
public class BtnsMainPanel extends javax.swing.JPanel {

    private JTable tblResults;
    private MainWindow principal;
    private InitialData initialData;
    
    /**
     * Creates new form BtnsMainPanel
     */
    public BtnsMainPanel(ResultsPanel resultsPanel, MainWindow principal){
        this.tblResults = resultsPanel.getTblResults();
        
        initialData = new InitialData();
        
        this.principal = principal;
        this.setTblResults(initialData.getReservas());
        
        
        initComponents();
    }

    public JTable getTblResults() {
        return tblResults;
    }
    public void setTblResults(ArrayList<Reserva> reservas) {
        String[] headers = {"idReserva", "Clase", "idPasajero", "Nombre Completo", "idVuelo", "Origen", "Destino", "Fecha"};
        this.tblResults.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int fila, int columna) {
                return false;
            }
        };
        tableModel.setColumnIdentifiers(headers);
        
        this.tblResults.setModel(tableModel);
        for(int i=0; i<reservas.size(); i++){
            tableModel.addRow(reservas.get(i).toArray());
        }
        tblResults.getColumnModel().getColumn(3).setPreferredWidth(200);
        tblResults.getColumnModel().getColumn(4).setPreferredWidth(60);
        tblResults.getColumnModel().getColumn(5).setPreferredWidth(110);
        tblResults.getColumnModel().getColumn(6).setPreferredWidth(110);
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newBtn = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JLabel();
        editBtn = new javax.swing.JLabel();
        reservaTF = new javax.swing.JTextField();
        pasajeroTF = new javax.swing.JTextField();
        labelReserva = new javax.swing.JLabel();
        labelPasajero = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 100));
        setPreferredSize(new java.awt.Dimension(1000, 180));

        newBtn.setBackground(new java.awt.Color(255, 255, 255));
        newBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        newBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newBtn.setText("NUEVO");
        newBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newBtn.setOpaque(true);
        newBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newBtnMouseExited(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 255, 255));
        deleteBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        deleteBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteBtn.setText("ELIMINAR");
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.setOpaque(true);
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteBtnMouseExited(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 255, 255));
        editBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        editBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editBtn.setText("EDITAR");
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.setOpaque(true);
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editBtnMouseExited(evt);
            }
        });

        reservaTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        reservaTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                reservaTFKeyReleased(evt);
            }
        });

        pasajeroTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        pasajeroTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pasajeroTFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pasajeroTFKeyTyped(evt);
            }
        });

        labelReserva.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelReserva.setText("idReserva");

        labelPasajero.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        labelPasajero.setText("idPasajero");

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        loginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn.setText("ENTRAR");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setOpaque(true);
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelReserva)
                    .addComponent(labelPasajero))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(reservaTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(pasajeroTF))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reservaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelReserva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasajeroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPasajero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtnMouseClicked
        principal.crearPanel(0, newBtn.getText(), "", "");
    }//GEN-LAST:event_newBtnMouseClicked

    private void newBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtnMouseEntered
        newBtn.setBackground(new Color(17, 153, 250));
        newBtn.setForeground(Color.white);
    }//GEN-LAST:event_newBtnMouseEntered

    private void newBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newBtnMouseExited
        newBtn.setBackground(Color.white);
        newBtn.setForeground(Color.black);
    }//GEN-LAST:event_newBtnMouseExited

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        
        int filaSel = tblResults.getSelectedRow();
        
        if(filaSel==-1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna reserva para eliminar");
            return;
        }
        
        if(new InitialData().deleteReserva(tblResults.getValueAt(filaSel, 0).toString())>0){
            DefaultTableModel model = (DefaultTableModel) this.tblResults.getModel();
            model.removeRow(filaSel);
        }
        
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void deleteBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseEntered
        deleteBtn.setBackground(new Color(17, 153, 250));
        deleteBtn.setForeground(Color.white);
    }//GEN-LAST:event_deleteBtnMouseEntered

    private void deleteBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseExited
        deleteBtn.setBackground(Color.white);
        deleteBtn.setForeground(Color.black);
    }//GEN-LAST:event_deleteBtnMouseExited

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        int filaSel = tblResults.getSelectedRow();
        
        if(filaSel==-1){
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna reserva para editar");
            return;
        }
        
        principal.crearPanel(0, "EDITAR", "", tblResults.getValueAt(filaSel, 0).toString());
        
    }//GEN-LAST:event_editBtnMouseClicked

    private void editBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseEntered
        editBtn.setBackground(new Color(17, 153, 250));
        editBtn.setForeground(Color.white);
    }//GEN-LAST:event_editBtnMouseEntered

    private void editBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseExited
        editBtn.setBackground(Color.white);
        editBtn.setForeground(Color.black);
    }//GEN-LAST:event_editBtnMouseExited

    private void reservaTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_reservaTFKeyReleased
        this.setTblResults(initialData.getFilteredReservas(this.pasajeroTF.getText().trim(),this.reservaTF.getText().trim()));
    }//GEN-LAST:event_reservaTFKeyReleased

    private void pasajeroTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasajeroTFKeyReleased
        this.setTblResults(initialData.getFilteredReservas(this.pasajeroTF.getText().trim(),this.reservaTF.getText().trim()));
    }//GEN-LAST:event_pasajeroTFKeyReleased

    private void pasajeroTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pasajeroTFKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
           (caracter > '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
           evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_pasajeroTFKeyTyped

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        principal.crearPanel(2, "", "", "");
    }//GEN-LAST:event_loginBtnMouseClicked

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setBackground(new Color(17, 153, 250));
        loginBtn.setForeground(Color.white);
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(Color.white);
        loginBtn.setForeground(Color.black);
    }//GEN-LAST:event_loginBtnMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel editBtn;
    private javax.swing.JLabel labelPasajero;
    private javax.swing.JLabel labelReserva;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel newBtn;
    private javax.swing.JTextField pasajeroTF;
    private javax.swing.JTextField reservaTF;
    // End of variables declaration//GEN-END:variables
}
