/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InitialData;
import java.awt.Color;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ivan
 */
public class Login extends javax.swing.JPanel {

    private InitialData initialData;
    private MainWindow principal;
    
    /**
     * Creates new form Login
     */
    public Login(MainWindow principal) {
        
        initialData = new InitialData();
        this.principal = principal;
        
        initComponents();
        
        new TextPrompt("Id Empleado", idEmpleadoTF);
        new TextPrompt("Contraseña", passwordTF);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconoLbl = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        idEmpleadoTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JPasswordField();
        iconoBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        iconoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/logoAvion.png"))); // NOI18N

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        loginBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginBtn.setText("LOG IN");
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.setOpaque(true);
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtnMouseExited(evt);
            }
        });

        idEmpleadoTF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N

        passwordTF.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        passwordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTFKeyPressed(evt);
            }
        });

        iconoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/avion.png"))); // NOI18N
        iconoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 414, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(passwordTF)
                    .addComponent(idEmpleadoTF))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(iconoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(idEmpleadoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        //Comprobar Campos
        
        if(comprobarCampos()==2) JOptionPane.showMessageDialog(null, "Ingrese su usuario");
        else if(comprobarCampos()==3) JOptionPane.showMessageDialog(null, "Ingrese su contraseña");
        else{
            
            if(initialData.correctLogin(idEmpleadoTF.getText().trim(), passwordTF.getText().toString())){
                
                principal.crearPanel(3, "", "", "");
                
            }else{
                JOptionPane.showMessageDialog(null, "Credenciales Incorrectas");
            }
            
        }
        
    }//GEN-LAST:event_loginBtnMouseClicked

    private void iconoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoBtnMouseClicked
        principal.dispose();
        new MainWindow();
    }//GEN-LAST:event_iconoBtnMouseClicked

    private void passwordTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTFKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER && KeyboardFocusManager.getCurrentKeyboardFocusManager().getFocusOwner()==evt.getComponent()){
            loginBtnMouseClicked(new MouseEvent(this, WIDTH, WIDTH, WIDTH, WIDTH, WIDTH, WIDTH, true));
        }
    }//GEN-LAST:event_passwordTFKeyPressed

    private void loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseEntered
        loginBtn.setBackground(new Color(17, 153, 250));
        loginBtn.setForeground(Color.white);
    }//GEN-LAST:event_loginBtnMouseEntered

    private void loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseExited
        loginBtn.setBackground(Color.white);
        loginBtn.setForeground(Color.black);
    }//GEN-LAST:event_loginBtnMouseExited

    
    private int comprobarCampos(){
        
        if(idEmpleadoTF.getText().equals("")) return 2;
        if(passwordTF.getText().toString().equals("")) return 3;
        
        return 1;        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconoBtn;
    private javax.swing.JLabel iconoLbl;
    private javax.swing.JTextField idEmpleadoTF;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JPasswordField passwordTF;
    // End of variables declaration//GEN-END:variables
}
