/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import controller.InitialData;

/**
 *
 * @author Ivan
 */
public class PasajeroPanel extends javax.swing.JPanel {

    InitialData initialData;
    MainWindow principal;
    
    /**
     * Creates new form PasajeroPanel
     */
    public PasajeroPanel(MainWindow principal) {
        
        initComponents();
        
        this.principal = principal;
        initialData = new InitialData();
        
        this.generoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Otro","Mujer", "Hombre"}));
    }

    public void setIdPasajero(String idTF) {
        this.idTF.setText(idTF);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombresLbl = new javax.swing.JLabel();
        edadLbl = new javax.swing.JLabel();
        apellidosLbl = new javax.swing.JLabel();
        generoLbl = new javax.swing.JLabel();
        nombresTF = new javax.swing.JTextField();
        apellidosTF = new javax.swing.JTextField();
        generoCbx = new javax.swing.JComboBox<>();
        registrarBtn = new javax.swing.JLabel();
        tituloLbl = new javax.swing.JLabel();
        idLabl = new javax.swing.JLabel();
        idTF = new javax.swing.JTextField();
        edadTF = new javax.swing.JTextField();
        iconoBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        nombresLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        nombresLbl.setText("Nombres");

        edadLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        edadLbl.setText("Edad");

        apellidosLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        apellidosLbl.setText("Apellidos");

        generoLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        generoLbl.setText("Genero");

        nombresTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        apellidosTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        generoCbx.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        generoCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        registrarBtn.setBackground(new java.awt.Color(255, 255, 255));
        registrarBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        registrarBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registrarBtn.setText("REGISTRAR");
        registrarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarBtn.setOpaque(true);
        registrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrarBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrarBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrarBtnMouseExited(evt);
            }
        });

        tituloLbl.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        tituloLbl.setText("NUEVO REGISTRO");

        idLabl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        idLabl.setText("ID");

        idTF.setEditable(false);
        idTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        edadTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        edadTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadTFKeyTyped(evt);
            }
        });

        iconoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/avion.png"))); // NOI18N
        iconoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombresLbl)
                    .addComponent(apellidosLbl)
                    .addComponent(edadLbl)
                    .addComponent(generoLbl)
                    .addComponent(idLabl))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(apellidosTF)
                    .addComponent(nombresTF)
                    .addComponent(generoCbx, 0, 109, Short.MAX_VALUE)
                    .addComponent(idTF)
                    .addComponent(edadTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(iconoBtn)
                .addGap(291, 291, 291)
                .addComponent(tituloLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 303, Short.MAX_VALUE)
                .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconoBtn)
                    .addComponent(tituloLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabl)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombresLbl)
                    .addComponent(nombresTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidosLbl)
                    .addComponent(apellidosTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadLbl)
                    .addComponent(edadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generoLbl)
                    .addComponent(generoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registrarBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarBtnMouseEntered
        registrarBtn.setBackground(new Color(17, 153, 250));
        registrarBtn.setForeground(Color.white);
    }//GEN-LAST:event_registrarBtnMouseEntered

    private void registrarBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarBtnMouseExited
        registrarBtn.setBackground(Color.white);
        registrarBtn.setForeground(Color.black);
    }//GEN-LAST:event_registrarBtnMouseExited

    private void edadTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadTFKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
           (caracter > '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
           evt.consume();  // ignorar el evento de teclado
        }else if (edadTF.getText().length() == 3){
            evt.consume();
        }
    }//GEN-LAST:event_edadTFKeyTyped

    private void registrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarBtnMouseClicked
        
        int correct = comprobarCampos();
        
        if(correct==1){
            
            int confirm = JOptionPane.showConfirmDialog(this, "¿Desea registrar al usuario:"
                    + "\n"+nombresTF.getText()+" "+apellidosTF.getText()+"\nCon identificacion: "+idTF.getText());
            
            if(confirm==0){
                initialData.crearPasajero(idTF.getText(), nombresTF.getText(), apellidosTF.getText(), edadTF.getText(), generoCbx.getSelectedItem().toString());
                ReservaPanel.finalizarRegistro();
                principal.dispose();
                new MainWindow();
            }
            
        }else{
            switch(correct){
                case 2: JOptionPane.showMessageDialog(null, "Ingrese sus nombres");     break;
                case 3: JOptionPane.showMessageDialog(null, "Ingrese sus apellidos");   break;
                case 4: JOptionPane.showMessageDialog(null, "Ingrese su edad");         break;
                default: JOptionPane.showMessageDialog(null, "Edad no válida");
            }
        }
        
    }//GEN-LAST:event_registrarBtnMouseClicked

    private void iconoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoBtnMouseClicked
        principal.dispose();
        new MainWindow();
    }//GEN-LAST:event_iconoBtnMouseClicked

    private int comprobarCampos(){
        
        if(nombresTF.getText().trim().equals("")) return 2;
        if(apellidosTF.getText().trim().equals("")) return 3;
        if(edadTF.getText().trim().equals("")) return 4;
        try{
            if(Integer.parseInt(edadTF.getText())>130) return 5;
        }catch(Exception ex){
            return 6; 
        }
        return 1;
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidosLbl;
    private javax.swing.JTextField apellidosTF;
    private javax.swing.JLabel edadLbl;
    private javax.swing.JTextField edadTF;
    private javax.swing.JComboBox<String> generoCbx;
    private javax.swing.JLabel generoLbl;
    private javax.swing.JLabel iconoBtn;
    private javax.swing.JLabel idLabl;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel nombresLbl;
    private javax.swing.JTextField nombresTF;
    private javax.swing.JLabel registrarBtn;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
