/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.InitialData;
import java.awt.Color;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Avion;

/**
 *
 * @author Ivan
 */
public class VueloPanel extends javax.swing.JPanel {

    private MainWindow principal;
    private String fechaFinal;
    private InitialData initialData;
    
    /**
     * Creates new form VueloPanel
     */
    public VueloPanel(MainWindow principal) {
        
        this.principal = principal;
        this.fechaFinal = "";
        
        initComponents();
        
        initialData = new InitialData();
        
        ArrayList<Avion> aviones = initialData.getAviones();
        String[] arr = new String[aviones.size()];
        
        for(int i=0; i<aviones.size(); i++)
            arr[i] = aviones.get(i).toString();
        
        this.avionCbx.setModel(new DefaultComboBoxModel<>(arr));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avionLbl = new javax.swing.JLabel();
        ciudadOrigenLbl = new javax.swing.JLabel();
        ciudadDestinoLbl = new javax.swing.JLabel();
        fechaLbl = new javax.swing.JLabel();
        precioLbl = new javax.swing.JLabel();
        ciudadOrigenTF = new javax.swing.JTextField();
        ciudadDestinoTF = new javax.swing.JTextField();
        precioTF = new javax.swing.JTextField();
        avionCbx = new javax.swing.JComboBox<>();
        fechaChooser = new com.toedter.calendar.JDateChooser();
        crearBtn = new javax.swing.JLabel();
        tituloLbl = new javax.swing.JLabel();
        iconoBtn = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));

        avionLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        avionLbl.setText("Avion");

        ciudadOrigenLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        ciudadOrigenLbl.setText("Ciudad Origen");

        ciudadDestinoLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        ciudadDestinoLbl.setText("Ciudad Destino");

        fechaLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        fechaLbl.setText("Fecha");

        precioLbl.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        precioLbl.setText("Precio");

        ciudadOrigenTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ciudadOrigenTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ciudadOrigenTFKeyTyped(evt);
            }
        });

        ciudadDestinoTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        ciudadDestinoTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ciudadDestinoTFKeyTyped(evt);
            }
        });

        precioTF.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        precioTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioTFKeyTyped(evt);
            }
        });

        avionCbx.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        avionCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        fechaChooser.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        crearBtn.setBackground(new java.awt.Color(255, 255, 255));
        crearBtn.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        crearBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        crearBtn.setText("CREAR");
        crearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crearBtn.setOpaque(true);
        crearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                crearBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                crearBtnMouseExited(evt);
            }
        });

        tituloLbl.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        tituloLbl.setText("NUEVO VUELO");

        iconoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/avion.png"))); // NOI18N
        iconoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconoBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(precioLbl)
                    .addComponent(fechaLbl)
                    .addComponent(ciudadDestinoLbl)
                    .addComponent(ciudadOrigenLbl)
                    .addComponent(avionLbl))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(ciudadDestinoTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precioTF, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(192, 192, 192)
                        .addComponent(crearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ciudadOrigenTF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(avionCbx, javax.swing.GroupLayout.Alignment.LEADING, 0, 160, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(iconoBtn)
                .addGap(310, 310, 310)
                .addComponent(tituloLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tituloLbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avionLbl)
                    .addComponent(avionCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudadOrigenLbl)
                    .addComponent(ciudadOrigenTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudadDestinoLbl)
                    .addComponent(ciudadDestinoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaLbl)
                    .addComponent(fechaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLbl)
                    .addComponent(precioTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void crearBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseExited
        crearBtn.setBackground(Color.white);
        crearBtn.setForeground(Color.black);
    }//GEN-LAST:event_crearBtnMouseExited

    private void crearBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseEntered
        crearBtn.setBackground(new Color(17, 153, 250));
        crearBtn.setForeground(Color.white);
    }//GEN-LAST:event_crearBtnMouseEntered

    private void iconoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconoBtnMouseClicked
        principal.dispose();
        new MainWindow();
    }//GEN-LAST:event_iconoBtnMouseClicked

    private void crearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearBtnMouseClicked
        
        int correct = comprobarCampos();
                
        if(correct==1){
            
            String[] nombre = ciudadOrigenTF.getText().trim().split(" ");
            String origen = "";

            for(String palabra: nombre){
                origen += palabra.substring(0, 1).toUpperCase() + palabra.substring(1).toLowerCase() + " ";
            }

            nombre = ciudadDestinoTF.getText().trim().split(" ");
            String destino = "";

            for(String palabra: nombre){
                destino += palabra.substring(0, 1).toUpperCase() + palabra.substring(1).toLowerCase() + " ";
            }
            
            correct = JOptionPane.showConfirmDialog(null, "¿Desea crear el vuelo:"
                                        + "\n"+origen+" - "+destino
                                        + "\nPara el avion: "+avionCbx.getSelectedItem().toString()
                                        + "\nPara el dia: "+fechaFinal+"\nCon un costo estandar de: "+precioTF.getText());
            
            if(correct==0){
                
                //Crear el vuelo
                initialData.crearVuelo( avionCbx.getSelectedItem().toString().split(" ")[0].trim(),
                                        origen.trim(), destino.trim(),
                                        fechaFinal.trim(), precioTF.getText().trim());
                
                principal.crearPanel(3, "", "", "");
                
            }
            
        }else{
            switch(correct){
                case 2: JOptionPane.showMessageDialog(null, "Fecha no válida");             break;
                case 3: JOptionPane.showMessageDialog(null, "Seleccione un avión");         break;
                case 4: JOptionPane.showMessageDialog(null, "Ingrese una ciudad Origen");   break;
                case 5: JOptionPane.showMessageDialog(null, "Ingrese una ciudad Destino");  break;
                case 7: JOptionPane.showMessageDialog(null, "La ciudad de origen y de destino son la misma"); break;
                case 8: JOptionPane.showMessageDialog(null, "El avion seleccionado se encuentra ocupado para otro vuelo en esta fecha"); break;
                default: JOptionPane.showMessageDialog(null, "El precio no es válido");
            }
        }
        
        
        System.out.println();
        
    }//GEN-LAST:event_crearBtnMouseClicked

    private void ciudadOrigenTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciudadOrigenTFKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter > '0') &&
           (caracter < '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
           evt.consume();  // ignorar el evento de teclado
        }
        
    }//GEN-LAST:event_ciudadOrigenTFKeyTyped

    private void ciudadDestinoTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciudadDestinoTFKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter > '0') &&
           (caracter < '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
           evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_ciudadDestinoTFKeyTyped

    private void precioTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioTFKeyTyped
        char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if(((caracter < '0') ||
           (caracter > '9')) &&
           (caracter != '\b' /*corresponde a BACK_SPACE*/))
        {
           evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_precioTFKeyTyped

    private int comprobarCampos(){
        
        try{
            fechaFinal = new SimpleDateFormat("yyyy-MM-dd").format(fechaChooser.getDate());
        }catch(Exception e){
            return 2;
        }
        if(fechaChooser.getDate().compareTo(new Date())<0) return 2;
        if(avionCbx.getSelectedIndex()==0) return 3;
        if(ciudadOrigenTF.getText().trim().equals("")) return 4;
        if(ciudadDestinoTF.getText().trim().equals("")) return 5;
        if(ciudadOrigenTF.getText().toUpperCase().equals(ciudadDestinoTF.getText().toUpperCase())) return 7;
        try{
            long costo = Long.parseLong(precioTF.getText().trim());
            if(costo<0) return 6;
        }catch(Exception e){
            e.printStackTrace();
            return 6;
        }
        
        if(!initialData.isFree(Integer.parseInt(avionCbx.getSelectedItem().toString().split("-")[0].trim()), fechaFinal))
            return 8;
        
        return 1;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> avionCbx;
    private javax.swing.JLabel avionLbl;
    private javax.swing.JLabel ciudadDestinoLbl;
    private javax.swing.JTextField ciudadDestinoTF;
    private javax.swing.JLabel ciudadOrigenLbl;
    private javax.swing.JTextField ciudadOrigenTF;
    private javax.swing.JLabel crearBtn;
    private com.toedter.calendar.JDateChooser fechaChooser;
    private javax.swing.JLabel fechaLbl;
    private javax.swing.JLabel iconoBtn;
    private javax.swing.JLabel precioLbl;
    private javax.swing.JTextField precioTF;
    private javax.swing.JLabel tituloLbl;
    // End of variables declaration//GEN-END:variables
}
